### ISSUE TITLE
How to add new data to log?

### ISSUE THREAD

**Issue by lakshaytalkstocomputer** [lingster/drf-api-tracking#18]
How to change the models to log new data like OS or anything else.?
I saw in mixin, you are calling         
```
super(BaseLoggingMixin, self).__init__(*args, **kwargs) 
```
in __init__ . Does not it calls itself?

**Comment by lingster** [comment]
I'm not sure what you mean by logging new data like os? Can you give me an example of what you are trying to do?You add the mixing as part of the view class and any rest api calls to that endpoint will be logged. On 2 Jun 2020 15:11, Lakshay Sagar Rana <notifications@github.com> wrote:
How to change the models to log new data like OS or anything else.?
I saw in mixin, you are calling
super(BaseLoggingMixin, self).__init__(*args, **kwargs) 

in init . Does not it calls itself?

**Comment by lakshaytalkstocomputer** [comment]
Ya i actually wanted to store the browser name and operating system. So i inherited the model and added new fields

**Comment by lingster** [comment]
I think one way to do this, is to subclass the APIRequestLog class adding your additional new fields. We would then have to add a function get_log_model() similar to the django get_user_model() which we could then specify via settings.py  a different model to use for logging. The LoggingMixin() class could be updated to use the model specified in the config.

**Comment by lakshaytalkstocomputer** [comment]
Thabkyoou and also could you please run makemigrations and the push the code. my deploy pipleline has a segment which checks if  there are migrations to perform. I cannot run makemigration as some of the fields would have to set the value. So i push the migration file. but everytime the pipeline downloads your app the check fails tellin me to run makemigration

**Comment by lingster** [comment]
Hi, thanks for pointing out the missing migrations. I've updated this and pushed a new version(1.7.4).
I have also added a test django project which can be used to generate migrations if there are changes to the models in this library in future. Let me know if any futher issues, if not I will close off this ticket.

**Comment by lakshaytalkstocomputer** [comment]
Thanks for the update. Really appreciate. Let me know if you need contributor maybe.

**Comment by lingster** [comment]
@lakshaytalkstocomputer : hi it would be great to have an additional contributor to this project, it's not particularly active but I've just sent you an invite. Feel free to create new issues or if you have some good ideas we can try to improve this project together.
