### ISSUE TITLE
is DRF version 3.11 supported? 

### ISSUE THREAD

**Issue by MScMechatronics** [lingster/drf-api-tracking#19]
I do not get any logging output on my DigitalOcean server for hosting DRF api. This is a blocker in my development since without the logging from drf-api-tracking my requests becomes a black box. 

Following set-up is employed on the server:
Python 3.6
Django 3.0.6
DRF 3.11 

Please help me, I'm stuck

**Comment by MScMechatronics** [comment]
I was not able to get drf-api-tracking work. Instead I ended up using https://github.com/Rhumbix/django-request-logging

**Comment by lingster** [comment]
Hi DRF 3.11 is included in the tests, so it should work, can you provide example of your code otherwise if this is no longer an issue I will close this.

**Comment by k34n4y138** [comment]
make sure the LoggingMixin is the first thing Inherited by the View class.
`
class MyPostsManagementAPIViewset(=>LoggingMixin<=,ViewSet, generics.CreateAPIView,
                                  generics.RetrieveUpdateAPIView):
....
`

**Comment by k34n4y138** [comment]
make sure the LoggingMixin is the first thing Inherited by the View class.
`
class MyPostsManagementAPIViewset(=>`**LoggingMixin**`<=,ViewSet, generics.CreateAPIView,
                                  generics.RetrieveUpdateAPIView):
....
`

**Comment by lingster** [comment]
Closing issue as no response from original poster
