### ISSUE TITLE
Requests from IPv6 IP addresses not logged

### ISSUE THREAD

**Issue by cjh79** [lingster/drf-api-tracking#20]
Problem is the fix to https://github.com/lingster/drf-api-tracking/issues/12, which breaks logging on any IPv6 addresses since they are colon-separated hex numbers and results in an exception like (on postgres):

`psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type inet: "2604"`

I am working on a PR to fix this which I should have ready shortly. I am filing this issue in case someone googles that exception. And unfortunately this means that since that fix, anyone using this has been missing out on logs from any IPv6 addresses...

**Comment by lingster** [comment]
PR has been merged and available in 1.7.5 release.
