### ISSUE TITLE
X_FORWARDED_FOR into list and store Client IP

### ISSUE THREAD

**Issue by patec** [lingster/drf-api-tracking#27]
Per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For), X_FORWARDED_FOR can be a list and thus breaks when trying to store in remote_addr which is a GenericIPAddressField.  The first value in the X_FORWARDED_FOR list will be the client ip, and the remaining are all proxy IPs and can be able to be stripped away.  I've opened a PR to fix this: https://github.com/lingster/drf-api-tracking/pull/26

**Comment by lingster** [comment]
Thanks for the PR, merged and deployed in 1.7.6
