### ISSUE TITLE
BaseLoggingMixin causing RequestDataTooBig exception

### ISSUE THREAD

**Issue by ibest30** [lingster/drf-api-tracking#47]
Can someone please help me to understand the purpose of:
`self.log["data"] = self._clean_data(request.body)`  

in the `initial` method of the BaseLoggingMixin?

I'm accepting large files and `self._clean.data(request.body)` is raising a RequestDataTooBig exception.

What I don't understand is why we're calling it in the first place, since we're going to overwrite `self.log["data"]` almost immediately anyways:
```
self.log["data"] = self._clean_data(request.body)
        super(BaseLoggingMixin, self).initial(request, *args, **kwargs)

        try:
            data = self.request.data.dict()

        except AttributeError:
            data = self.request.data
        self.log["data"] = self._clean_data(data)

```
If someone could provide me a little insight, I'd appreciate it.

**Comment by ibest30** [comment]
After some further investigation, I see that the request.body string gets returned in `finalize_response`  if there's an authorization error:
```
    if self._clean_data(request.query_params.dict()) == {}:
    self.log.update({"query_params": self.log["data"]})

```
I wonder if it's worth having an option to disable this function on a per view basis and instead pass an empty string to query_params?  Besides the RequestDataTooBig problem, there's also the problem that any data passed doesn't get masked when the converted bytestring gets passed to query_params.

**Comment by lingster** [comment]
that sounds like a good idea, perhaps we could have a global options parameter defined in settings.py which could then be overridden at class level.we should Also trim the log to the length of that field or have option to log to stdoutOn 9 Apr 2021 02:33, ibest30 ***@***.***> wrote:
After some further investigation, I see that the request.body string gets returned in finalize_response  if there's an authorization error:
    if self._clean_data(request.query_params.dict()) == {}:
    self.log.update({"query_params": self.log["data"]})


I wonder if it's worth having an option to disable this function on a per view basis and instead pass an empty string to query_params?  Besides the RequestDataTooBig problem, there's also the problem that any data passed doesn't get masked when the converted bytestring gets passed to query_params.
