### ISSUE TITLE
When is the new version released?

### ISSUE THREAD

**Issue by Brechard** [lingster/drf-api-tracking#50]
I found this library that I think is amazing but I really need the just added feature for the decode_request_body. The version in pypi hasn't been updated for a while and I would like to know when do you plan on releasing a new version.

**Comment by lingster** [comment]
Hi, 
I'm just getting ready to deploy your changes. For some reason the unit tests were not working, so I have fixed that. 
It seems like one of the tests is failing, could you help take a look?

https://github.com/lingster/drf-api-tracking/runs/2481801906?check_suite_focus=true
Once sorted, I will schedule a release. 
Thanks!

**Comment by Brechard** [comment]
Thanks for your message, I was not the developer that created the feature but I found the mistake as you asked and created a [pull request](https://github.com/lingster/drf-api-tracking/pull/52)

**Comment by lingster** [comment]
Thanks for the PR, new version 1.8.0 has been released
