### ISSUE TITLE
how to convert to dictionary

### ISSUE THREAD

**Issue by Kiel-Hyre** [lingster/drf-api-tracking#63]
so im getting all the logs response and I tried using  import json but it does not work since its not literally converted to json. I also tried ast  it works if all were string but it will error when it encounters <InMemory...> so any idea how to revert it back? Thank you

**Comment by lingster** [comment]
have you tried pinning to a previous version? 
are you able to share the full errors/code you are using to help investigate further?

**Comment by Kiel-Hyre** [comment]
as of the version were using 1.7.8 (in requirements.txt)  and here im just trying to covert back the response to dictionary via json.loads yet the expected error from json.loads were the JSONError (from the library) in which it stuck to covert because of the <InMemory> and other file/images connected. Another thing to note it cannot be converted too since the quotations used in the response and others were singles instead of double.  I tried library ast too it works fine if there were no files/images but yep as expected it cannot convert it due to <InMemory> related thing.

**Comment by Kiel-Hyre** [comment]
ok seems the response data itself had no problem, all photos or files were converted to a link. The problem here was the query or data that had InMemoryUpload and a single quotes. I unsterstand why it does work that way, though is there was any workaround to atleast convert those InMemory to string so I can convert it via ast.
